@startuml
!include <c4/C4_Component>

title  Диаграмма на уровне компонентов для микросервиса управления освещением Lighting_System_Service

Container(lighting_system_service, "Сервис управления освещением", "Java, Spring Boot", "Управляет системой освещения.") {
    Component(api, lighting_system_service, "API", "REST API, обрабатывает запросы от API Gateway")
    Component(command_handler, lighting_system_service, "Обработчик команд", "Обрабатывает команды.")
    Component(state_manager, lighting_system_service, "Менеджер состояния", "Управляет состоянием системы")
    Component(db_access_layer, lighting_system_service, "Уровень доступа к БД", "Взаимодействует с базой данных")
    Component(event_publisher, lighting_system_service, "Публикатор событий", "Публикует события в Kafka")
    Component(business_logic, lighting_system_service, "Бизнес-логика", "Реализует логику работы ")

    Rel(api, command_handler, "Вызывает", "REST")
    Rel(command_handler, state_manager, "Изменяет состояние", "")
    Rel(state_manager, db_access_layer, "Сохраняет состояние", "")
    Rel(state_manager, event_publisher, "Публикует событие (изменение состояния)", "")
    Rel(business_logic, state_manager, "Вызывает изменение состояния", "")
    Rel(business_logic, db_access_layer, "Запрашивает данные", "")
}

@enduml