@startuml
!include <c4/C4_Component>

title  Диаграмма на уровне компонентов для микросервиса мониторинга температуры Temperature_Monitoring_Service

Container(temperature_monitoring_service, "Сервис у мониторинга температуры", "Java, Spring Boot", "Взаимодействует с датчиками температуры.") {
    Component(api, temperature_monitoring_service, "API", "REST API, обрабатывает запросы от API Gateway")
    Component(command_handler, temperature_monitoring_service, "Обработчик команд", "Обрабатывает команды.")
    Component(state_manager, temperature_monitoring_service, "Менеджер состояния", "Управляет состоянием системы")
    Component(db_access_layer, temperature_monitoring_service, "Уровень доступа к БД", "Взаимодействует с базой данных")
    Component(event_publisher, temperature_monitoring_service, "Публикатор событий", "Публикует события в Kafka")
    Component(business_logic, temperature_monitoring_service, "Бизнес-логика", "Реализует логику работы ")

    Rel(api, command_handler, "Вызывает", "REST")
    Rel(command_handler, state_manager, "Изменяет состояние", "")
    Rel(state_manager, db_access_layer, "Сохраняет состояние", "")
    Rel(state_manager, event_publisher, "Публикует событие (изменение состояния)", "")
    Rel(business_logic, state_manager, "Вызывает изменение состояния", "")
    Rel(business_logic, db_access_layer, "Запрашивает данные", "")
}

@enduml